// Generated by CoffeeScript 1.10.0
(function() {
  var TwitterClient;

  TwitterClient = (function() {
    function TwitterClient() {
      this.params = this.urlParams();
      this.client = new Codebird();
      this.client.setConsumerKey("1wpgjt1LL7ihzYjqq6ZkzNNaC", "yVvsSBqhKlEscc9bq27CKP6rZm5l7GCxbCCJBUInpBfcVRxsRp");
      this.client.setToken("4764576000-BgKuC4pHN7X4iqZF1TckBvTenaQzkKU1pipc65S", "qoyPEeJ7zjvG1UeNqfuPsDKE58adIAJTVvyqi2L5Aordh");
      this.search("knowuh");
    }

    TwitterClient.prototype.urlParams = function() {
      var i, key, len, params, query, rawVars, ref, v, val;
      query = window.location.search.substring(1);
      rawVars = query.split("&");
      params = {};
      for (i = 0, len = rawVars.length; i < len; i++) {
        v = rawVars[i];
        ref = v.split("="), key = ref[0], val = ref[1];
        params[key] = decodeURIComponent(val);
      }
      return params;
    };

    TwitterClient.prototype.callClient = function(method, opts, callback) {
      var handler;
      handler = function(result, err) {
        if (err) {
          console.log(err);
        }
        if (result) {
          return callback(result);
        }
      };
      return this.client.__call(method, opts, handler);
    };

    TwitterClient.prototype.authenticate = function() {
      var auth;
      auth = (function(_this) {
        return function(response) {
          _this.bearerToken = response.access_token;
          return _this.client.setBearerToken(_this.bearerToken);
        };
      })(this);
      return this.callClient("oauth2_token", {}, auth);
    };

    TwitterClient.prototype.search = function(term) {
      var callback;
      callback = function(reply) {
        return console.log(reply);
      };
      return this.callClient("search_tweets", {
        q: term
      }, callback);
    };

    return TwitterClient;

  })();

  $(document).ready(function() {
    var client;
    return client = new TwitterClient();
  });

}).call(this);

//# sourceMappingURL=twitter_client.js.map
